### ISSUE TITLE
Can't find service with key

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#915] opened 2017-05-19 19:29 UTC
### Installation information

- jumpscale version: 8.2.0 (dfd1f642098fdb7d611386380b463aa94378a356)
- operating system: Ubuntu 16.04

### Detailed description
While trying to deploy a huge blueprint (250+ new services), it fails to create a run.

### Steps to reproduce
Install a resourcepool on be-g8-3.
Try to deploy a storagecluster.
Can deploy the storagecluster by submitting the following post request to the resourcepool api server:
```
POST /storageclusters HTTP/1.1
Host: 10.244.188.186:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "servers": 70,
    "label": "bigmomma",
    "nodes": [
        "0cc47a3b3d6a",
        "0cc47a3aad5a",
        "0cc47a3b3d98",
        "0cc47a3b3eb2",
        "0cc47aabad1c",
        "0cc47aab670a",
        "0cc47a6b2c1c",
        "0cc47aab66e2",
        "0cc47aab6702",
        "0cc47aab6444"
    ],
    "driveType": "ssd"
}
```

### Relevant stacktraces
![afbeelding](https://cloud.githubusercontent.com/assets/15246294/26263563/9e9f778c-3cd9-11e7-893f-e6460559fb2a.png)

**Comment by rkhamis** [comment] 2017-05-21 08:04
Duplicate of https://github.com/Jumpscale/jumpscale_core8/issues/898

**Closed by rkhamis** 2017-05-21 08:04 UTC
Labels: priority_critical, state_inprogress, type_bug
